<a href="https://colab.research.google.com/github/arpit1729/ma22c007_2023_PL/blob/main/Assignments/Assignment_6/Pairwise_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

x = np.random.rand(5)

Y = np.subtract.outer(x, x)
print(Y)

[[ 0.          0.04940516 -0.24695756 -0.10849914  0.21880118]
 [-0.04940516  0.         -0.29636272 -0.15790429  0.16939602]
 [ 0.24695756  0.29636272  0.          0.13845842  0.46575874]
 [ 0.10849914  0.15790429 -0.13845842  0.          0.32730031]
 [-0.21880118 -0.16939602 -0.46575874 -0.32730031  0.        ]]


In [3]:
A = np.zeros((5,5))
for i in range(5):
  for j in range (5):
    A[i][j]=x[i]-x[j]

print(A)

[[ 0.          0.04940516 -0.24695756 -0.10849914  0.21880118]
 [-0.04940516  0.         -0.29636272 -0.15790429  0.16939602]
 [ 0.24695756  0.29636272  0.          0.13845842  0.46575874]
 [ 0.10849914  0.15790429 -0.13845842  0.          0.32730031]
 [-0.21880118 -0.16939602 -0.46575874 -0.32730031  0.        ]]
