<a href="https://colab.research.google.com/github/arpit1729/ma22c007_2023_PL/blob/main/Assignments/Assignment_5/Row_Swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

def given_swap_row(i, j, A):
    temp = A[i, :]  #temp ='i'th row of A
    A[i, :] = A[j, :]
    A[j, :] = temp
    return A

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = given_swap_row(0, 2, A)

print(result)

[[7 8 9]
 [4 5 6]
 [7 8 9]]


In [9]:
def modifide_swap_rows(i, j, A):
  """

  swap row i and j in a numpy array A.

  Parameters:
  - i: Index of the first row to swap.
  - j: Index of the second row to swap.
  - A: The nupmy array with row i and j swapped.

  returns:
  -A: The numpy array with rows i and j swapped.
  """

  if i< 0 or i >= len(A) or j < 0 or j >= len(A):
     print("Invalid row indices.")
  else:
     temp = A[i, :].copy()
     A[i, :] = A[j, :]
     A[j, :] = temp
     return A

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

restult = modifide_swap_rows(0, 2, A)

print(result)

[[7 8 9]
 [4 5 6]
 [7 8 9]]
